#-----------------------------------------------------------
# Passwordy
#
# this program selects a random word from a pre-defined
#  list and the user must try to guess the word.
#
#-----------------------------------------------------------

import random


# function that displays the main menu and stores the user's selection.
def main_menu():
    user_selection = input("""Main Menu
    (p) Play a round
    (i) View instructions
    (q) Quit
    Please select an option: """)
    
    if user_selection.casefold() == 'p':
        round_start()
    elif user_selection.casefold() == 'i':
        rules_game()
    elif user_selection.casefold() == 'q':
        quit_game()
    else:
        input('Invalid selection. Press enter to return to the Main Menu.')
        main_menu()

# function that picks a random word and starts a new round.
def round_start():
    housekeeping()
    curr_keyword = choose_pass()
    
    
# function that displays the rules of the game and then returns to the main menu.
def rules_game():
    print("""
    - A random, English keyword will be generated by the computer.
    - Your task is to guess the keyword using clues based on your previous guesses.
    - When you submit a valid guess, the computer will tell you whether each letter is one of three states:
    
    \tO --> Correct letter and position
    \tW --> Correct letter but wrong position
    \tx --> Letter is not in the keyword
    
    - Letters can repeat in the word, but it is up to you to figure out if that is the case.
    """)
    input('Press Enter to return to the Main Menu.')
    main_menu()

# function that asks the user to confirm if they want to quit the 
#  program and either quits or returns to the main menu.
def quit_game():
    user_selection = input("Quit the program? (y/n): ")
    if user_selection.casefold() == 'y':
        quit()
    else:
        main_menu()

# function that randomly chooses one of the words from the list.
def choose_pass():
    random.seed()
    rand_num = random.randint(0,len(poss_keywords)-1)
    return poss_keywords[rand_num]
    # for debugging
    #curr_keyword = poss_keywords[rand_num]
    #print(len(poss_keywords))
    #print(rand_num)
    #print(curr_keyword)

# function to clean up between rounds
def housekeeping():
    pass


# read the list of keywords and assign to variable
with open('word_list.txt') as f:
    poss_keywords = []
    for i in f:
        poss_keywords.append(i.strip())

# for debugging 
#print(poss_keywords)
#choose_pass()


# Welcome message
print("Welcome to Wurdle! The game of guessing words!")

# Start main loop
main_menu()

# for debugging
#print(user_selection)


